
    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782540','1782540','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1761527','1761527','1',sysdate,'rhq',sysdate,'rhq','37','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1705117','1705117','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1708258','1708258','1',sysdate,'rhq',sysdate,'rhq','32','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1991581','1991581','1',sysdate,'rhq',sysdate,'rhq','51','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1849622','1849622','1',sysdate,'rhq',sysdate,'rhq','35','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1708046','1708046','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1700759','1700759','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1762195','1762195','1',sysdate,'rhq',sysdate,'rhq','31','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1703208','1703208','1',sysdate,'rhq',sysdate,'rhq','51','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1705102','1705102','1',sysdate,'rhq',sysdate,'rhq','31','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1992593','1992593','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782745','1782745','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1774744','1774744','1',sysdate,'rhq',sysdate,'rhq','15','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1704518','1704518','1',sysdate,'rhq',sysdate,'rhq','22','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782546','1782546','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709192','1709192','1',sysdate,'rhq',sysdate,'rhq','31','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1705601','1705601','1',sysdate,'rhq',sysdate,'rhq','31','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1788050','1788050','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1767465','1767465','1',sysdate,'rhq',sysdate,'rhq','43','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781862','1781862','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709008','1709008','1',sysdate,'rhq',sysdate,'rhq','11','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782529','1782529','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1988911','1988911','1',sysdate,'rhq',sysdate,'rhq','54','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1737672','1737672','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1787006','1787006','1',sysdate,'rhq',sysdate,'rhq','36','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1736349','1736349','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1767612','1767612','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1769728','1769728','1',sysdate,'rhq',sysdate,'rhq','63','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1788863','1788863','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1700659','1700659','1',sysdate,'rhq',sysdate,'rhq','37','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1767617','1767617','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782729','1782729','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709272','1709272','1',sysdate,'rhq',sysdate,'rhq','42','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782704','1782704','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709576','1709576','1',sysdate,'rhq',sysdate,'rhq','34','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1767923','1767923','1',sysdate,'rhq',sysdate,'rhq','36','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1708066','1708066','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781943','1781943','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709419','1709419','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1708880','1708880','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782717','1782717','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1734287','1734287','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1707772','1707772','1',sysdate,'rhq',sysdate,'rhq','31','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709029','1709029','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782579','1782579','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782727','1782727','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1763879','1763879','1',sysdate,'rhq',sysdate,'rhq','41','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1767506','1767506','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709592','1709592','1',sysdate,'rhq',sysdate,'rhq','35','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1785676','1785676','1',sysdate,'rhq',sysdate,'rhq','34','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1708956','1708956','1',sysdate,'rhq',sysdate,'rhq','64','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1737678','1737678','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1769099','1769099','1',sysdate,'rhq',sysdate,'rhq','65','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1788623','1788623','1',sysdate,'rhq',sysdate,'rhq','52','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1767686','1767686','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781948','1781948','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1701784','1701784','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709677','1709677','1',sysdate,'rhq',sysdate,'rhq','43','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782535','1782535','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1707420','1707420','1',sysdate,'rhq',sysdate,'rhq','33','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1788066','1788066','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1707006','1707006','1',sysdate,'rhq',sysdate,'rhq','11','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1992857','1992857','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1784140','1784140','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1707482','1707482','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709083','1709083','1',sysdate,'rhq',sysdate,'rhq','11','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1849862','1849862','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781833','1781833','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1700761','1700761','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1769723','1769723','1',sysdate,'rhq',sysdate,'rhq','63','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781572','1781572','1',sysdate,'rhq',sysdate,'rhq','33','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782772','1782772','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1767618','1767618','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1708068','1708068','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709738','1709738','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1784180','1784180','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1701730','1701730','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1702565','1702565','1',sysdate,'rhq',sysdate,'rhq','34','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1767716','1767716','1',sysdate,'rhq',sysdate,'rhq','45','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709719','1709719','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1707931','1707931','1',sysdate,'rhq',sysdate,'rhq','62','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1700362','1700362','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1982362','1982362','1',sysdate,'rhq',sysdate,'rhq','50','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1778840','1778840','1',sysdate,'rhq',sysdate,'rhq','46','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782594','1782594','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782778','1782778','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781595','1781595','1',sysdate,'rhq',sysdate,'rhq','33','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782787','1782787','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1708673','1708673','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1708988','1708988','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1705113','1705113','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1783396','1783396','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1767471','1767471','1',sysdate,'rhq',sysdate,'rhq','43','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709207','1709207','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1784166','1784166','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1705833','1705833','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709748','1709748','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1784198','1784198','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709767','1709767','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1707053','1707053','1',sysdate,'rhq',sysdate,'rhq','32','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782598','1782598','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1707660','1707660','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781946','1781946','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1774349','1774349','1',sysdate,'rhq',sysdate,'rhq','22','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1706310','1706310','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1992597','1992597','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1780511','1780511','1',sysdate,'rhq',sysdate,'rhq','32','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1733612','1733612','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709700','1709700','1',sysdate,'rhq',sysdate,'rhq','45','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782746','1782746','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1705011','1705011','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709717','1709717','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1700056','1700056','1',sysdate,'rhq',sysdate,'rhq','12','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1788059','1788059','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782518','1782518','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1767927','1767927','1',sysdate,'rhq',sysdate,'rhq','36','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709766','1709766','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709711','1709711','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1708028','1708028','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782539','1782539','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1706309','1706309','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1767464','1767464','1',sysdate,'rhq',sysdate,'rhq','43','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709973','1709973','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1706451','1706451','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782567','1782567','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709733','1709733','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709720','1709720','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1787788','1787788','1',sysdate,'rhq',sysdate,'rhq','45','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781480','1781480','1',sysdate,'rhq',sysdate,'rhq','41','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709981','1709981','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782728','1782728','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1707089','1707089','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1706156','1706156','1',sysdate,'rhq',sysdate,'rhq','35','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1982798','1982798','1',sysdate,'rhq',sysdate,'rhq','51','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709190','1709190','1',sysdate,'rhq',sysdate,'rhq','31','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1715031','1715031','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781659','1781659','1',sysdate,'rhq',sysdate,'rhq','33','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1662003','1662003','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1707320','1707320','1',sysdate,'rhq',sysdate,'rhq','13','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1708034','1708034','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1708095','1708095','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1705036','1705036','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1788071','1788071','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1707084','1707084','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1753522','1753522','1',sysdate,'rhq',sysdate,'rhq','14','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1784199','1784199','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1769736','1769736','1',sysdate,'rhq',sysdate,'rhq','63','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709761','1709761','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1767653','1767653','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1700268','1700268','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709752','1709752','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1708025','1708025','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1705762','1705762','1',sysdate,'rhq',sysdate,'rhq','42','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1708093','1708093','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1707036','1707036','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782718','1782718','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1767712','1767712','1',sysdate,'rhq',sysdate,'rhq','45','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782569','1782569','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709995','1709995','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1783393','1783393','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781926','1781926','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1708977','1708977','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1700760','1700760','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1705955','1705955','1',sysdate,'rhq',sysdate,'rhq','50','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1769727','1769727','1',sysdate,'rhq',sysdate,'rhq','63','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782777','1782777','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1660760','1660760','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782769','1782769','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1787759','1787759','1',sysdate,'rhq',sysdate,'rhq','45','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709880','1709880','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1763361','1763361','1',sysdate,'rhq',sysdate,'rhq','41','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1767096','1767096','1',sysdate,'rhq',sysdate,'rhq','43','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1786830','1786830','1',sysdate,'rhq',sysdate,'rhq','61','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1858966','1858966','1',sysdate,'rhq',sysdate,'rhq','46','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781533','1781533','1',sysdate,'rhq',sysdate,'rhq','50','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1700782','1700782','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1708007','1708007','1',sysdate,'rhq',sysdate,'rhq','11','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1701727','1701727','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1706068','1706068','1',sysdate,'rhq',sysdate,'rhq','11','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1787367','1787367','1',sysdate,'rhq',sysdate,'rhq','43','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1783399','1783399','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781532','1781532','1',sysdate,'rhq',sysdate,'rhq','50','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1750620','1750620','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1718528','1718528','1',sysdate,'rhq',sysdate,'rhq','32','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782798','1782798','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1788056','1788056','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709009','1709009','1',sysdate,'rhq',sysdate,'rhq','11','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781879','1781879','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709274','1709274','1',sysdate,'rhq',sysdate,'rhq','42','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1707664','1707664','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782528','1782528','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1708689','1708689','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781573','1781573','1',sysdate,'rhq',sysdate,'rhq','33','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782577','1782577','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782596','1782596','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1715030','1715030','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1705504','1705504','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782785','1782785','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781822','1781822','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1763080','1763080','1',sysdate,'rhq',sysdate,'rhq','41','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781896','1781896','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1705318','1705318','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1737813','1737813','1',sysdate,'rhq',sysdate,'rhq','43','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709892','1709892','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709193','1709193','1',sysdate,'rhq',sysdate,'rhq','31','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782538','1782538','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1774967','1774967','1',sysdate,'rhq',sysdate,'rhq','43','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1707086','1707086','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1992815','1992815','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1706857','1706857','1',sysdate,'rhq',sysdate,'rhq','32','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781941','1781941','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1705534','1705534','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1701664','1701664','1',sysdate,'rhq',sysdate,'rhq','32','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1707082','1707082','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781816','1781816','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1705731','1705731','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709203','1709203','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1707665','1707665','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1705605','1705605','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1708894','1708894','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782784','1782784','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781944','1781944','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781938','1781938','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709758','1709758','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1786787','1786787','1',sysdate,'rhq',sysdate,'rhq','33','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1784183','1784183','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1709755','1709755','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1757607','1757607','1',sysdate,'rhq',sysdate,'rhq','44','2');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1992861','1992861','1',sysdate,'rhq',sysdate,'rhq','44','3');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782782','1782782','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1781924','1781924','1',sysdate,'rhq',sysdate,'rhq','44','1');
    

    INSERT INTO TB_USER_ROUTE_RULE(RULE_ID,RULE_NAME,SECTION_NO,STATUS,INSERT_TIME,INSERT_STAFF_ID,LAST_MOD_TIME,
    LAST_MOD_STAFF_ID,PROVINCE,MOBIL_CORP)VALUES(sys_guid(),'1782536','1782536','1',sysdate,'rhq',sysdate,'rhq','44','1');
    